### PR TITLE
Improves ghpages

### PR DESCRIPTION
**Pull request by jhlch**
You can test this change by pip installing mkdocs and then running mkdocs serve from the root dir.

### CODE REVIEW

**Comment by holdenk** [comment]
Changes look good to me, I can test it after brunch :)

**Comment by jhlch** [comment]
The poutine brunch will lull you into a state of universal acceptance. SGTM.

**Comment by holdenk** [comment]
oh w00t! Just ran mkdocs, looks AWESOME to me.

**Comment by holdenk** [comment]
Does this mean we don't have to write jekyll anymore?

**Comment by jhlch** [comment]
Correct

**Pull request merged**
